server:
    tomcat:
      uri-encoding: UTF-8
    port: 8087
spring:
    http:
     encoding:
          force: true
          charset: utf-8
          enabled: true
    datasource:
        name: db_lottery
        url: jdbc:mysql://127.0.0.1:3306/db_lottery?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        logSlowSql: true
mybatis:
  #XXXMapper.xml文件所在的位置
    mapperLocations: classpath:mapper/*.xml
  #实体对象对应的位置
    typeAliasesPackage: com.huato.lottery.pojo